"use client";

import Image from "next/image";
import Link from "next/link";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "https://api.sigil.codes";

export default function AgentLandingPage() {
  return (
    <div className="min-h-screen bg-[#050505] text-white">
      {/* Nav */}
      <nav className="border-b border-white/5">
        <div className="max-w-4xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="font-bold text-lg flex items-center gap-2">
            <Image src="/sigil-symbol.svg" alt="Sigil" width={24} height={24} />
            <span className="font-display text-[22px] tracking-[0.25em] uppercase">SIGIL</span>
            <span className="text-[#00FF88] text-[11px] font-mono uppercase tracking-widest ml-2">for agents</span>
          </Link>
          <Link
            href="/dashboard"
            className="text-sm text-white/40 hover:text-white transition-colors"
          >
            Human Dashboard →
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <div className="max-w-4xl mx-auto px-6 py-16">
        <div className="text-center space-y-4 mb-16">
          <h1 className="text-4xl font-bold">
            Agent Wallet Security API
          </h1>
          <p className="text-lg text-white/40 max-w-2xl mx-auto">
            Deploy and manage Sigil smart wallets programmatically.
            3-tier co-signing, policy engine, and session keys — all via REST API.
          </p>
        </div>

        {/* Conversational Setup */}
        <div className="space-y-8">
          <div className="bg-gradient-to-r from-[#00FF88]/10 to-[#00FF88]/10 border border-[#00FF88]/30 rounded-xl p-8">
            <h2 className="text-xl font-bold mb-3">🤖 Conversational Setup</h2>
            <p className="text-white/40 mb-4">
              The recommended flow: your agent asks the owner a few questions, collects their preferences, then handles the deployment. No technical knowledge needed from the owner.
            </p>
            <pre className="bg-[#0A0A0A] rounded-lg p-4 text-sm font-mono overflow-x-auto">
{`// Step 1: Fetch the setup wizard
const wizard = await fetch("${API_URL}/v1/agent/setup/wizard");
const { questions, exampleConversation } = await wizard.json();

// Step 2: Walk through questions with your owner
// The wizard returns each question with explanations,
// defaults, and example conversation flow

// Step 3: Once you have all answers, call guided setup
const setup = await fetch("${API_URL}/v1/agent/setup", { ... });

// Step 4: Present contract calls to owner for signing`}
            </pre>
            <p className="text-xs text-white/40 mt-3">
              Try it: <code className="text-[#00FF88]">GET {API_URL}/v1/agent/setup/wizard</code>
            </p>
          </div>

          <div className="bg-white/[0.02] border border-white/5 rounded-xl p-8">
            <h2 className="text-xl font-bold mb-6">Direct API Quick Start</h2>

            {/* Step 1 */}
            <div className="space-y-6">
              <div>
                <div className="flex items-center gap-3 mb-3">
                  <span className="w-7 h-7 rounded-full bg-[#00FF88]/20 text-[#00FF88] text-sm font-bold flex items-center justify-center">1</span>
                  <h3 className="font-semibold">Authenticate</h3>
                </div>
                <p className="text-sm text-white/40 mb-3 ml-10">
                  Use an API key (generated by the wallet owner from the dashboard) or a delegation signature.
                </p>
                <pre className="bg-[#0A0A0A] rounded-lg p-4 text-sm font-mono overflow-x-auto ml-10">
{`// Option A: API Key (simpler)
const auth = await fetch("${API_URL}/v1/agent/auth/api-key", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ apiKey: "sgil_your_key_here" }),
});
const { token } = await auth.json();

// Option B: Delegation signature (more secure)
const auth = await fetch("${API_URL}/v1/agent/auth/delegation", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    ownerAddress: "0x...",
    agentIdentifier: "my-agent",
    signature: "0x...",      // EIP-712 signed by owner
    expiresAt: 1739404800,
    nonce: "unique-random-string",
  }),
});
const { token } = await auth.json();`}
                </pre>
              </div>

              {/* Step 2 */}
              <div>
                <div className="flex items-center gap-3 mb-3">
                  <span className="w-7 h-7 rounded-full bg-[#00FF88]/20 text-[#00FF88] text-sm font-bold flex items-center justify-center">2</span>
                  <h3 className="font-semibold">Deploy or Get Setup Instructions</h3>
                </div>
                <p className="text-sm text-white/40 mb-3 ml-10">
                  Use the guided setup endpoint — it returns all contract calls you need.
                </p>
                <pre className="bg-[#0A0A0A] rounded-lg p-4 text-sm font-mono overflow-x-auto ml-10">
{`const setup = await fetch("${API_URL}/v1/agent/setup", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    Authorization: \`Bearer \${token}\`,
  },
  body: JSON.stringify({
    agentKey: "0xYourAgentKeyAddress",
    chainId: 43113,  // Avalanche Fuji
    maxTxValueEth: 0.1,
    dailyLimitEth: 1.0,
    allowedTargets: ["0xUniswapRouter", "0xAavePool"],
    sessionKey: {
      key: "0xEphemeralKeyAddress",
      validForHours: 24,
      spendLimitEth: 0.5,
    },
  }),
});

const { steps } = await setup.json();
// Returns ordered list of contract calls to execute`}
                </pre>
              </div>

              {/* Step 3 */}
              <div>
                <div className="flex items-center gap-3 mb-3">
                  <span className="w-7 h-7 rounded-full bg-[#00FF88]/20 text-[#00FF88] text-sm font-bold flex items-center justify-center">3</span>
                  <h3 className="font-semibold">Monitor & Manage</h3>
                </div>
                <pre className="bg-[#0A0A0A] rounded-lg p-4 text-sm font-mono overflow-x-auto ml-10">
{`// Check wallet status
const status = await fetch(
  "${API_URL}/v1/agent/wallets/0xYourWallet",
  { headers: { Authorization: \`Bearer \${token}\` } }
);

// Update policy
await fetch("${API_URL}/v1/agent/wallets/0xYourWallet/policy", {
  method: "PUT",
  headers: {
    "Content-Type": "application/json",
    Authorization: \`Bearer \${token}\`,
  },
  body: JSON.stringify({
    maxTxValue: "200000000000000000", // 0.2 AVAX
    dailyLimit: "2000000000000000000", // 2 AVAX
  }),
});`}
                </pre>
              </div>
            </div>
          </div>

          {/* API Endpoints Reference */}
          <div className="bg-white/[0.02] border border-white/5 rounded-xl p-8">
            <h2 className="text-xl font-bold mb-6">API Reference</h2>

            <div className="space-y-4">
              <h3 className="text-sm font-semibold text-white/40 uppercase tracking-wider">Setup Wizard</h3>
              <Endpoint method="GET" path="/v1/agent/setup/wizard" desc="Conversational setup guide — questions, defaults, example dialogue" />

              <h3 className="text-sm font-semibold text-white/40 uppercase tracking-wider mt-6">Authentication</h3>
              <Endpoint method="POST" path="/v1/agent/auth/api-key" desc="Authenticate with API key" />
              <Endpoint method="POST" path="/v1/agent/auth/delegation" desc="Authenticate with delegation signature" />
              <Endpoint method="GET" path="/v1/agent/delegation-info" desc="Get EIP-712 domain & types for delegation" />

              <h3 className="text-sm font-semibold text-white/40 uppercase tracking-wider mt-6">Wallet Setup</h3>
              <Endpoint method="POST" path="/v1/agent/setup" desc="Guided all-in-one setup — returns all contract calls needed" />
              <Endpoint method="POST" path="/v1/agent/wallets/deploy" desc="Get deployment config & instructions" />
              <Endpoint method="POST" path="/v1/agent/wallets/register" desc="Register deployed wallet in Sigil DB" />

              <h3 className="text-sm font-semibold text-white/40 uppercase tracking-wider mt-6">Management</h3>
              <Endpoint method="GET" path="/v1/agent/wallets/:address" desc="Full wallet status" scope="wallet:read" />
              <Endpoint method="PUT" path="/v1/agent/wallets/:address/policy" desc="Update policy" scope="policy:write" />
              <Endpoint method="POST" path="/v1/agent/wallets/:address/targets" desc="Manage target whitelist" scope="targets:write" />
              <Endpoint method="POST" path="/v1/agent/wallets/:address/functions" desc="Manage function whitelist" scope="targets:write" />
              <Endpoint method="POST" path="/v1/agent/wallets/:address/session-keys" desc="Create session key" scope="session-keys:write" />
              <Endpoint method="POST" path="/v1/agent/wallets/:address/token-policies" desc="Set token allowance policy" scope="policy:write" />
            </div>
          </div>

          {/* Security */}
          <div className="bg-white/[0.02] border border-white/5 rounded-xl p-8">
            <h2 className="text-xl font-bold mb-4">Security Model</h2>
            <div className="grid grid-cols-2 gap-6">
              <div className="space-y-2">
                <h3 className="font-semibold text-[#00FF88] text-sm">✓ Agents CAN</h3>
                <ul className="text-sm text-white/40 space-y-1">
                  <li>• Deploy new wallets</li>
                  <li>• Configure policies & limits</li>
                  <li>• Manage target/function whitelists</li>
                  <li>• Create session keys</li>
                  <li>• View wallet status & audit logs</li>
                  <li>• Set token allowance policies</li>
                </ul>
              </div>
              <div className="space-y-2">
                <h3 className="font-semibold text-[#F04452] text-sm">✗ Agents CANNOT</h3>
                <ul className="text-sm text-white/40 space-y-1">
                  <li>• Withdraw or transfer funds</li>
                  <li>• Freeze or unfreeze accounts</li>
                  <li>• Transfer ownership</li>
                  <li>• Upgrade contract implementation</li>
                  <li>• Execute timelock transactions</li>
                  <li>• Modify recovery guardians</li>
                </ul>
              </div>
            </div>
          </div>

          {/* Supported Chains */}
          <div className="bg-white/[0.02] border border-white/5 rounded-xl p-8">
            <h2 className="text-xl font-bold mb-4">Supported Chains</h2>
            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 bg-[#0A0A0A] rounded-lg border border-white/5">
                <h3 className="font-semibold">Avalanche C-Chain</h3>
                <p className="text-sm text-white/40 mt-1">Chain ID: 43114</p>
                <code className="text-xs text-[#00FF88] break-all">Factory: 0x7b7D00ED8Ac494c191DCaBD312d39563F0c76c3B</code>
              </div>
              <div className="p-4 bg-[#0A0A0A] rounded-lg border border-white/5">
                <h3 className="font-semibold">Avalanche Fuji</h3>
                <p className="text-sm text-white/40 mt-1">Chain ID: 43113</p>
                <code className="text-xs text-[#00FF88] break-all">Factory: 0x65d47d9a49268E989B2D1a8697c2b60c1Ef83321</code>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function Endpoint({ method, path, desc, scope }: { method: string; path: string; desc: string; scope?: string }) {
  const methodColors: Record<string, string> = {
    GET: "text-[#00FF88]",
    POST: "text-[#00FF88]",
    PUT: "text-[#F4A524]",
    DELETE: "text-[#F04452]",
  };

  return (
    <div className="flex items-center gap-3 py-2 px-3 bg-[#0A0A0A] rounded-lg">
      <span className={`text-xs font-bold w-12 ${methodColors[method] ?? ""}`}>{method}</span>
      <code className="text-sm font-mono flex-1">{path}</code>
      <span className="text-xs text-white/40">{desc}</span>
      {scope && (
        <span className="text-xs px-1.5 py-0.5 rounded bg-[#00FF88]/10 text-[#00FF88]">{scope}</span>
      )}
    </div>
  );
}
